# Generated by Django 2.1.3 on 2018-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsltters', '0002_auto_20181117_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=299)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=11)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.ManyToManyField(to='newsltters.NewsLetterUser')),
            ],
        ),
    ]
